export default [
	{ active: false, navIconName: "nav-object", navName: "По проекту" },
	{ active: false, navIconName: "nav-object", navName: "Объекты" },
	{ active: false, navIconName: "nav-object", navName: "РД" },
	{ active: false, navIconName: "nav-object", navName: "МТО" },
	{ active: true, navIconName: "nav-object", navName: "СМР" },
	{ active: false, navIconName: "nav-object", navName: "ГРАФИК" },
	{ active: false, navIconName: "nav-object", navName: "МиМ" },
	{ active: false, navIconName: "nav-object", navName: "Рабочие" },
	{ active: false, navIconName: "nav-object", navName: "Капвложения" },
	{ active: false, navIconName: "nav-object", navName: "Бюджет" },
	{ active: false, navIconName: "nav-object", navName: "Финансирование" },
	{ active: false, navIconName: "nav-object", navName: "Панорамы" },
	{ active: false, navIconName: "nav-object", navName: "Камеры" },
	{ active: false, navIconName: "nav-object", navName: "Поручения" },
	{ active: false, navIconName: "nav-object", navName: "Контрагенты" },
];
